### PR TITLE
Fixed array_multisort parameters error

### PR DESCRIPTION
**Pull request by AnrDaemon**

### CODE REVIEW

**Review by roxblnfk — APPROVED** [review]

**Comment by roxblnfk** [comment]
@msmakouz could you check why CI is broken here?

**Comment by msmakouz** [comment]
> @msmakouz could you check why CI is broken here?

Outdated version of the extension, fixed.

**Comment by roxblnfk** [comment]
Could you do the same for the `4.x` branch?

**Comment by AnrDaemon** [comment]
> Could you do the same for the `4.x` branch?

On the way.

**Pull request merged**
